### ISSUE TITLE
dashboard配置热点规则和系统规则不生效

### ISSUE THREAD

**Issue by ovenfrank** [lk0423/sentinel-dashboard#1]
流控和熔断生效了，但是热点和授权规则我测试的不生效，即使不用持久化，直接在dashboard上配置热点和授权规则也不生效，怎么回事

**Comment by ovenfrank** [comment]
> 虽然sentinel中规则持久化到nacos中成功了，但是当服务重启后规则在dashboard上面有，但是不生效，需要手动编辑一下重新保存一下才生效，是不是因为服务重启后规则没加载到内存中，所以没生效

**Comment by ovenfrank** [comment]
是我配错了。。打扰了

**Comment by ovenfrank** [comment]
流控和熔断生效了，但是热点和授权规则我测试的不生效，即使不用持久化，直接在dashboard上配置热点和授权规则也不生效，怎么回事

**Comment by ovenfrank** [comment]
热点规则和系统规则持久化生效了，但是配置了没有效果，不会出现fallback和blockhandler

**Comment by ovenfrank** [comment]
```yaml
      datasource:
        # 流控规则
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            username: ${spring.cloud.nacos.config.username}
            password: ${spring.cloud.nacos.config.password}
            namespace: ${sentinel.namespace}
            group-id: SENTINEL_GROUP
            data-id: "sentinel_rule_config-${spring.application.name}-flow-rules"
            # 规则类型：flow、degrade、param-flow、system、authority
            rule-type: flow
            data-type: json  #默认就是json
        # 熔断降级
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            username: ${spring.cloud.nacos.config.username}
            password: ${spring.cloud.nacos.config.password}
            namespace: ${sentinel.namespace}
            group-id: SENTINEL_GROUP
            data-id: "sentinel_rule_config-${spring.application.name}-degrade-rules"
            rule-type: degrade
        # 热点规则
#        param-flow:
#          nacos:
#            server-addr: ${spring.cloud.nacos.config.server-addr}
#            username: ${spring.cloud.nacos.config.username}
#            password: ${spring.cloud.nacos.config.password}
#            namespace: ${sentinel.namespace}
#            group-id: SENTINEL_GROUP
#            data-id: "sentinel_rule_config-${spring.application.name}-param-rules"
#            rule-type: param-flow
#            data-type: json
```
我把热点规则持久化的配置注释掉之后，热点规则就生效了，但是持久化又不行了
